name: unittests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  code_style:
    runs-on: 
       - ubuntu-latest-self
       - self-hosted

#steps:
#    - name: Checkout viv
#      uses: actions/checkout@v2
        
#    - name: Set up Python 3.8
#      uses: actions/setup-python@v2
#      with:
#        python-version: 3.8
          
#    - name: Install dependencies
#      run: pip install 'isort==5.*' black
#        
#    - name: Lint with isort
#      run: isort --profile black --length-sort --line-width 120 -c .
#        
#    - name: Lint with black
#      run: black -l 120 --check .
#        

commands:

  do_python_setup:
    description: "Setup python for testing"
    steps:
      - run:
          name: setup venv
          command: |
            python3 -m pip install -U wheel pip
            python3 -m pip install -r requirements.txt


  do_test_execution:
    description: "Execute unit tests via unittest"
    steps:
      - run:
          name: run tests
          command: |
            python3 -m unittest discover

  test_steps_python:
    description: "Python test steps"
    steps:
      - checkout

      - run:
          name: checkout vivtest files repo
          command: |
            git clone https://github.com/vivisect/vivtestfiles.git $VIVTESTFILES

      - run:
          name: install deps
          command: |
            sudo apt-get update
            sudo apt-get -qq install libfreetype6-dev liblcms2-dev ghostscript libffi-dev libjpeg-turbo-progs cmake imagemagick

      - do_python_setup

      - do_test_execution

jobs:

  python38:
    parallelism: 1
    docker:
      - image: circleci/python:3.8
        environment:
          VIVTESTFILES: /tmp/vivtestfiles
          PYVERS: 3.8

    working_directory: ~/repo

    steps:
      - test_steps_python

  python39:
    parallelism: 1
    docker:
      - image: circleci/python:3.9
        environment:
          VIVTESTFILES: /tmp/vivtestfiles
          PYVERS: 3.9

    working_directory: ~/repo

    steps:
      - test_steps_python

workflows:
  version: 2
  run_tests:
    jobs:

      - python39:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

      - python38:
          filters:
            tags:
              only: /.*/
            branches:
              only: /.*/

#  weekly:
#    triggers:
#      - schedule:
#          cron: "0 12 1 * *"
#          filters:
#            branches:
#              only:
#                - master
#    jobs:
#      - python39
